'use client'
import { Geist, Geist_Mono } from "next/font/google";
import { ProjectProvider } from './contexts/ProjectContext';
import Script from 'next/script';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ProjectProvider>
          {children}
        </ProjectProvider>
        
        <Script src="js/jquery.js" strategy="beforeInteractive" />
        <Script src="js/popper.min.js" strategy="beforeInteractive" />
        <Script src="js/bootstrap.min.js" strategy="beforeInteractive" />
        <Script src="js/jquery.mCustomScrollbar.concat.min.js" strategy="afterInteractive" />
        <Script src="js/jquery.fancybox.js" strategy="afterInteractive" />
        <Script src="js/appear.js" strategy="afterInteractive" />
        <Script src="js/owl.js" strategy="afterInteractive" />
        <Script src="js/wow.js" strategy="afterInteractive" />
        <Script src="js/parallax.min.js" strategy="afterInteractive" />
        <Script src="js/tilt.jquery.min.js" strategy="afterInteractive" />
        <Script src="js/jquery.paroller.min.js" strategy="afterInteractive" />
        <Script src="js/jquery-ui.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}